### ISSUE TITLE
Add Some New Projects In this Repository

### ISSUE THREAD

**Issue by thevirus69** [thevirus69/Project-Web-Android#1]

**Comment by Noburu-Hasashi** [comment]
I am willing to participate, what project do you want me to make?

**Comment by thevirus69** [comment]
> I am willing to participate, what project do you want me to make?

You can Add Any projects 
like Android Projects 
Any Website
Any DSA ques with solutions

**Comment by Noburu-Hasashi** [comment]
I'll add a code for python which prints an image in both colors and b&w using ASCII characters.
Is this project okay?

**Comment by thevirus69** [comment]
> I'll add a code for python which prints an image in both colors and b&w using ASCII characters. Is this project okay?

Yes you can 😊

**Comment by losermyluckwithyou007** [comment]
I have 10 to 15 android projects you can see my repo. Can I add any project

**Comment by thevirus69** [comment]
> I have 10 to 15 android projects you can see my repo. Can I add any project

😅 plz add any project

**Comment by losermyluckwithyou007** [comment]
> > I have 10 to 15 android projects you can see my repo. Can I add any project
> 
> 😅 plz add any project

I have created a PR please kindly check

**Comment by theanmolmalik** [comment]
Hi, there I am interested to work on this. Can you please assign it to me?

**Comment by deepak725** [comment]
Hi, there I want to assigned some projects. Please assign it to me.

**Comment by sanjay000111** [comment]
I am interested, I have submitted my pr kindly merge it

**Comment by Saurav-Sutaria** [comment]
hey @thevirus69 , I have added merge sort algorithm in DSA part, please review my PR #16

**Comment by debajyoti007-git** [comment]
Hey @thevirus69, I want to add a project on browser extensions which will quickly launch social media sites with just a click, kindly accept my PR #37.
